# Copyright 2025 The ChaosBlade Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosblade-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaosblade-operator
  template:
    metadata:
      labels:
        name: chaosblade-operator
    spec:
      serviceAccountName: chaosblade
      containers:
        - name: chaosblade-operator
          # Replace this with the built image name
          image: chaosbladeio/chaosblade-operator:0.6.0
          command: ["chaosblade-operator"]
          args:
            - --blade-version=0.6.0
            - --image-repo=chaosbladeio/chaosblade-tool
            - --pull-policy=IfNotPresent
            - --namespace=kube-system
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaosblade-operator"
