apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: chaosblade
  labels:
    name: chaosblade
roleRef:
  kind: ClusterRole
  name: chaosblade
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: chaosblade
    namespace: kube-system
