apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: node-network-delay-by-names
spec:
  experiments:
  - scope: node
    target: network
    action: delay
    desc: "delay pod network by names"
    matchers:
    - name: names
      value: ["node-example-01"]
    - name: interface
      value: ["eth0"]
    - name: time
      value: ["3000"]
    - name: offset
      value: ["1000"]
