{{- $ca := genCA "chaosblade-webhook-server-ca" 3650 }}
{{- $cn := "chaosblade-webhook-server" }}
{{- $dns1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $dns2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $dns1 $dns2) 3650 $ca }}

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: chaosblade-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: chaosblade-operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
webhooks:
  - clientConfig:
      caBundle: {{ $ca.Cert | b64enc | quote }}
      service:
        name: chaosblade-webhook-server
        namespace: {{ .Release.Namespace }}
        path: /mutating-pods
    name: "{{ .Chart.Name }}.{{ .Release.Namespace }}.svc"
    failurePolicy: Ignore
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
---
apiVersion: v1
kind: Secret
metadata:
  name: chaosblade-webhook-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app: chaosblade-operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
