apiVersion: v1
kind: Service
metadata:
  name: chaosblade-webhook-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    name: chaosblade-operator
